apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: demo-app
type: Opaque
data:
  # Base64 encoded password for 'postgres' user
  # Password is: password
  POSTGRES_PASSWORD: "cGFzc3dvcmQ="
  # Base64 encoded user, required if you don't use the default 'postgres'
  POSTGRES_USER: "cG9zdGdyZXM=" # postgres
