apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: demo-app
type: Opaque
data:
  # Base64 encoded password for 'postgres' user
  # Password is: Q$t2h!k3Pz7xW&dC
  POSTGRES_PASSWORD: "USR0aDIhazNPejd4VzZkQw=="
  # Base64 encoded user, required if you don't use the default 'postgres'
  POSTGRES_USER: "cG9zdGdyZXM=" # postgres
