apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: demo-app
spec:
  # This MUST match the storageClassName defined in the PV
  storageClassName: nfs-storage-class
  # Defines how the volume can be mounted (ReadWriteOnce is typical for single-node DBs)
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte of storage
