apiVersion: v1
kind: Service
metadata:
  # This name MUST match the host in the application's DATABASE_URL
  name: postgres-service
  namespace: demo-app
spec:
  # ClusterIP exposes the service only within the cluster (internal access only)
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432 # Service port
      targetPort: 5432 # Container port
