apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-app
  labels:
    app: demo-app
spec:
  # Run 3 replicas of the application for high availability
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app-container
        # IMPORTANT: Replace this with your actual image from ghcr.io
        image: ghcr.io/isstech/demo-app:latest
        ports:
        - containerPort: 8000
        env:
          # This failed because it relied on shell substitution inside the 'value' field:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-postgresql
              key: POSTGRES_URL
        
        # Pull resource limits from ConfigMap
        envFrom:
        - configMapRef:
            name: app-config
        # Health check to ensure the pod is ready to receive traffic
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
