# Create Namespace for the application
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
  labels:
    name: demo-app

---

# Create Secret for PostgreSQL credentials
apiVersion: v1
kind: Secret
metadata:
  name: postgres-postgresql
  namespace: demo-app
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/managed-by: demo-app
type: Opaque
data:
  # Base64 encoded password for 'postgres' user
  POSTGRES_PASSWORD: "cGFzc3dvcmQ=" # password (Original)
  POSTGRES_USER: "cG9zdGdyZXM=" # postgres
  POSTGRES_URL: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzLXBvc3RncmVzcWw6NTQzMi9kZW1vX2FwcF9kYg==" # postgresql://postgres:password@postgres-postgresql:5432/demo_app_db

---

# Create Service for the application
apiVersion: v1
kind: Service
metadata:
  name: demo-backend-service
  namespace: demo-app
spec:
  selector:
    app: demo-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8000

---

# Create ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo-app
data:
  # Database Configuration
  DB_NAME: "demo_app_db"
  DB_HOST: "postgres-postgresql"
  DB_PORT: "5432"

---

# NGINX Config for the front-end SvelteKit app
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
  namespace: demo-app
data:
  default.conf: |
    server {
        listen 80;
        
        # Serve the Svelte App
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # Proxy API calls to the internal Backend Service
        location /api/ {
            # "demo-backend-service" resolves INSIDE the cluster
            proxy_pass http://demo-backend-service.demo-app.svc.cluster.local:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
---

# Create PersistentVolumeClaim for PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: demo-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 

---

# Installing PostgreSQL as a StatefulSet
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: postgres
  namespace: demo-app
  annotations:
      kanister.kasten.io/blueprint: postgres-non-exclusive-backup
  labels:
        app: postgres
        app.kubernetes.io/instance: postgres    
spec:
  # Database usually runs as a single replica
  replicas: 1
  serviceName: postgres-postgresql 
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/instance: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-postgresql
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-postgresql
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: PGDATA
          value: "/var/lib/postgresql/data/db"

        # Mount the persistent volume for data
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc # References the PVC defined above

---

# Create Headless Service for PostgreSQL StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: postgres-postgresql
  namespace: demo-app
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432 
      targetPort: 5432

---

# Deploy the back-end FastAPI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
  namespace: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app-container
        image: ghcr.io/isstech/demo-backend:v1.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-postgresql
              key: POSTGRES_URL
        envFrom:
        - configMapRef:
            name: app-config
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20

---

# Deploy front-end SvelteKit app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
      - name: svelte-container
        image: ghcr.io/isstech/demo-frontend:v1.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # Mount the custom NGINX config
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: frontend-nginx-conf

---

# Frontend Service (Exposed as NodePort for local access)
apiVersion: v1
kind: Service
metadata:
  name: demo-frontend-service
  namespace: demo-app
spec:
  type: ClusterIP
  selector:
    app: demo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
