apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app-ingress
  namespace: demo-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - demo-app.apps.isstech-2.paas.safedc.net
    secretName: demo-app-tls-secret
  rules:
  - host: demo-app.apps.demoapp.paas.safedc.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-app-service 
            port:
              number: 80